# Generated by Django 4.0 on 2022-02-24 04:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_examplemodel_examplenonuploadmodel_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleNonUploadModel',
        ),
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='text',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='text',
        ),
    ]
