# Generated by Django 4.0 on 2022-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='blog/thumbnail/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='blog',
            table='',
        ),
    ]
