# Generated by Django 4.0 on 2022-02-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_options_blog_thumbnail_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': [-1]},
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
